#pragma once
#include <cstdint>

enum LaneBit{
    // Lane
    LANE_1 = 1 << 0,
    LANE_2 = 1 << 1,
    LANE_3 = 1 << 2,
    LANE_4 = 1 << 3,
    LANE_5 = 1 << 4,
    // SideFlick
    SIDEFLICK_LEFT = 1 << 5,
    SIDEFLICK_RIGHT = 1 << 6,
    // RectFlick
    RECTFLICK_LT = 1 << 7,
    RECTFLICK_LB = 1 << 8,
    RECTFLICK_RT = 1 << 9,
    RECTFLICK_RB = 1 << 10,
    // Wheel
    WHEEL_UP = 1 << 11,
    WHEEL_DOWN = 1 << 12,
    // 組み合わせ
    RECTFLICK_RIGHT = RECTFLICK_RT | RECTFLICK_RB,
    RECTFLICK_LEFT = RECTFLICK_LT | RECTFLICK_LB,
    RECTFLICK_UP = RECTFLICK_LT | RECTFLICK_RT,
    RECTFLICK_DOWN = RECTFLICK_LB | RECTFLICK_RB,
    RECTFLICK_LT_EX = RECTFLICK_LT | RECTFLICK_LB | RECTFLICK_RT,
    RECTFLICK_LB_EX = RECTFLICK_LB | RECTFLICK_LT | RECTFLICK_RB,
    RECTFLICK_RT_EX = RECTFLICK_RT | RECTFLICK_RB | RECTFLICK_LT,
    RECTFLICK_RB_EX = RECTFLICK_RB | RECTFLICK_RT | RECTFLICK_LB,
    RECTFLICK_ALL = RECTFLICK_LT | RECTFLICK_LB | RECTFLICK_RT | RECTFLICK_RB,
    WHEEL = WHEEL_UP | WHEEL_DOWN,
};

const int32_t kLaneBitCount = 13;// レーンのビット数