
name: MSBuild

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: SEED/SEED.sln
  BUILD_CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with: 
        msbuild-architecture: x64

    - name: Build
      run: |
        msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
